
-- SELEÇÃO PARA RECUPERAR DADOS CADASTRAIS DO PARTICIPANTE
SELECT A.CDFUN FUNDO, 
       A.CDPAT PATROCINADORA, 
       A.NRPLA PLANO,
       A.NRISC INSCRIÇÃO,
       A.NMPAR NOME
FROM   WEBPARTICIPANTES A;

-- SELEÇÃO PARA RECUPERAR DADOS DE MIGRAÇÃO
SELECT A.CDFUN FUNDO, 
       A.CDPAT PATROCINADORA, 
       A.NRPLA PLANO,
       A.NRISC INSCRI��O,
       A.DTMESREF REFERENCIA,
       A.VRSDO SALDO,
       A.VRCOT VALOR_DA_COTA,
       A.VRTOTCOT TOTAL_EM_COTAS,
       A.DTBPDS DATA_BPDS,
       A.VRATUCTA VALOR_BPDS
FROM   WEBMIGRACAO A;


-- SELEÇÃO PARA RECUPERAR MOVIMENTAÇÕES (CORPO DO EXTRATO)
SELECT A.CDFUN FUNDO, 
       A.CDPAT PATROCINADORA, 
       A.NRPLA PLANO,
       A.NRISC INSCRIÇÃO,
       A.DTMESREF REFERENCIA,
       NVL(B.VRSAL,0) SALÁRIO,
       A.VRCTBPAR PARTICIPANTE,
       A.VRCTBPAT PATROCINADORA,
       A.VRADI ADICIONAL,
       A.VRDED DEDUÇÃO,
       A.VRTOT TOTAL,
       A.VRCOT VR_COTA,
       A.QTCOT TOTAL_EM_COTAS
FROM   WEBMOVCTA A, WEBHISALARIOS B
WHERE  A.CDFUN = B.CDFUN
AND    A.CDPAT = B.CDPAT
AND    A.NRPLA = B.NRPLA
AND    A.NRISC = B.NRISC
AND    A.DTMESREF = B.DTMESREF;

-- SELEÇÃO PARA RECUPERAR SALDO DO PARTICIPANTE
SELECT A.CDFUN FUNDO, 
       A.CDPAT PATROCINADORA, 
       A.NRPLA PLANO,
       A.NRISC INSCRIÇÃO,
       A.DTMESAPR REFERENCIA,
       A.VRTOTCTA TOTAL_EM_COTAS,
       A.VRCOT VR_COTA,
       A.VRSDO SALDO_EM_REAIS,
       A.DCPFL DESCRIÇÃO DO PERFIL (SALDO) 
FROM   WEBSDOCTA A;

-- TROCA DE PERFIL ACONTECE QUANDO A COLUNA DCPFL ALTERA
-- EXEMPLO DE INSCRIÇÕS
-- 00058032
-- 00058040
-- 00058149
